### PR TITLE
✨feat: add selector for the amount of thumbnails per page

### LINKED ISSUE #48: [Suggestion] Number of Thumbnails per Page
Hello Devs,

In the grid view, would it be possible to choose the number of thumbnails per page in the settings? (for example, through multiple choice options).
Ideally, I would like to be able to display all the thumbnails on a single page.

Thank you in advance for considering this request and for the work you have already done.

Best regards.

### PR DESCRIPTION
**Pull request by NandyBa**
This PR introduces a feature requested by @jojodunet that allows users to choose the number of thumbnails displayed per page in the grid view. This enhancement is accessible at the end of the page and offers multiple choice options to suit different user preferences. Additionally, there is an option to display all thumbnails on a single page.

### CODE REVIEW

**Review by jycssu-com — DISMISSED** [review]
You should use 0 as the value to display all cards rather than the total length. Indeed, if you choose "All" with some filters/search, they will not all be visible when the filters/search are removed.

Ex: Search for "bird" -> choose "All" -> Clear search ==> Only one card visible

**Comment by jojodunet** [comment]
Hello @jycssu-com ,

I tried to contact @NandyBa directly but I haven’t received a response. 

Is it possible for you to make the modification on your side and merge the code, please? 

Thank you in advance for your response.

**Comment by NandyBa** [comment]
> You should use 0 as the value to display all cards rather than the total length. Indeed, if you choose "All" with some filters/search, they will not all be visible when the filters/search are removed.
> 
> Ex: Search for "bird" -> choose "All" -> Clear search ==> Only one card visible

Case handle in this last commit
I use Infinity instead of 0, it's make more sense

**Comment by NandyBa** [comment]
I have also rebased the develop branch

**Comment by NandyBa** [comment]
> Hello @jycssu-com ,
> 
> I tried to contact @NandyBa directly but I haven’t received a response.
> 
> Is it possible for you to make the modification on your side and merge the code, please?
> 
> Thank you in advance for your help.
> 
> Best regards.

Sorry, I responded but quite after, discord is not my main social, Telegram is more

**Review by ghost — APPROVED** [review]

**Pull request merged**
